server:
    port: 8848
    address: 127.0.0.1

spring:
    profiles:
        active: local # 默认使用local环境
    http:
        encoding:
            charset: UTF-8
            force: true
            enabled: true
    jpa:
        show-sql: true # 是否打印sql语句
        hibernate:
            ddl-auto: none # 是否自动生成DDL

swagger:
    switch: true

logging:
    level:
        root: INFO

### local环境的profile
---
spring:
    profiles: local
    datasource:
        platform: h2 # 使用H2数据库
        schema: classpath:resources/schema.sql # 数据库schema文件位置，DDL
        data: classpath:resources/data.sql # 数据库数据定义，DML
        initialization-mode: always # Spring boot 2.x

logging:
    level:
        top.jasonkayzk.swaggerDemo: DEBUG
        org.hibernate: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
