server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false

  http:
    encoding:
      charset: utf-8
      enabled: true

  #热部署
  devtools:
    restart:
      enabled: true

# mybatis-plus 设置
mybatis-plus:
  type-aliases-package: top.jasonkayzk.sso.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭mybatis-plus的banner
    banner: false

logging:
  config: classpath:logback.xml

